[package]
name = "password-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
magic-crypt = "3.1.12"
rust-crypto = "0.2.36"
serde_json = "1.0.105"
